CREATE PROFILE Quan_TriVien 
LIMIT 
    FAILED_LOGIN_ATTEMPTS 3 
    PASSWORD_LIFE_TIME 14 
    PASSWORD_GRACE_TIME 0 
    PASSWORD_REUSE_TIME UNLIMITED 
    PASSWORD_REUSE_MAX UNLIMITED 
    PASSWORD_VERIFY_FUNCTION NULL 
    PASSWORD_LOCK_TIME 30 
    IDLE_TIME UNLIMITED 
    CONNECT_TIME UNLIMITED;
    
    
    
    
CREATE PROFILE Nguoi_Dung1 LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 30
    PASSWORD_LOCK_TIME 1/1440; 
    
    
SELECT resource_name FROM DBA_PROFILES;
select * from nhanvien
select * from users
select * from khachhang

SELECT username, profile
FROM dba_users
WHERE username = 'WATTHE8';


ALTER USER watthe8 PROFILE Quan_TriVien;
SELECT RESOURCE_NAME, LIMIT
FROM DBA_PROFILES
WHERE PROFILE = 'QUAN_TRIVIEN';

SELECT RESOURCE_NAME, LIMIT
FROM DBA_PROFILES
WHERE PROFILE = (SELECT profile FROM dba_users WHERE username = 'WATTHE8');

INSERT INTO NHANVIEN (NHANVIENID, TENNHANVIEN, CHUCVU, SODIENTHOAI, NGAYSINH, DIACHI, NOISINH, MATKHAU)
VALUES ('NV3', 'L? Nguy?n Thi?n ??nh', 'ADMIN', '0708804070', TO_DATE('15-OCT-03', 'DD-MON-YY'), 'TP.HCM', NULL, '741C58C6680AF67F');

DELETE FROM KHACHHANG
WHERE KHACHHANGID = 'KH03';



